# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialise.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [3]:
%run initialise.py

ModuleNotFoundError: No module named 'mdutils'

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
np.__version__

'2.0.2'

#### 3. Create a null vector of size 10 (★☆☆)

In [5]:
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [7]:
arr.size

10

#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [8]:
np.info()

 info(object=None, maxwidth=76, output=None, toplevel='numpy')

Get help information for an array, function, class, or module.

Parameters
----------
object : object or str, optional
    Input object or name to get information about. If `object` is
    an `ndarray` instance, information about the array is printed.
    If `object` is a numpy object, its docstring is given. If it is
    a string, available modules are searched for matching objects.
    If None, information about `info` itself is returned.
maxwidth : int, optional
    Printing width.
output : file like object, optional
    File like object that the output is written to, default is
    ``None``, in which case ``sys.stdout`` will be used.
    The object has to be opened in 'w' or 'a' mode.
toplevel : str, optional
    Start search at this level.

Notes
-----
When used interactively with an object, ``np.info(obj)`` is equivalent
to ``help(obj)`` on the Python prompt or ``obj?`` on the IPython
prompt.

Examples
--------
>>> n

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [10]:
arr = np.zeros(10)
arr[4] = 1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
arr1 = np.arange(10, 49)
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [14]:
arr1[::-1]

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [15]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [19]:
arr2 = np.array([1, 2, 0, 0, 4, 0])
arr2.nonzero()

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [22]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [23]:
np.random.seed(42)
np.random.rand(3, 3, 3)

array([[[0.37454012, 0.95071431, 0.73199394],
        [0.59865848, 0.15601864, 0.15599452],
        [0.05808361, 0.86617615, 0.60111501]],

       [[0.70807258, 0.02058449, 0.96990985],
        [0.83244264, 0.21233911, 0.18182497],
        [0.18340451, 0.30424224, 0.52475643]],

       [[0.43194502, 0.29122914, 0.61185289],
        [0.13949386, 0.29214465, 0.36636184],
        [0.45606998, 0.78517596, 0.19967378]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
arr = np.random.rand(10, 10)
print(arr.min(), arr.max())

0.005522117123602399 0.9868869366005173


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
arr = np.random.rand(30)
print(arr.mean())

0.4585744124442792


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [28]:
arr = np.zeros((10,10))
arr[:,[0, -1]] = 1
arr[[0, -1], :] = 1
arr

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [29]:
np.pad(arr,1,'constant')

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [31]:
0 * np.nan

nan

In [32]:
np.nan == np.nan

False

In [33]:
np.inf > np.nan

False

In [34]:
np.nan - np.nan

nan

In [35]:
np.nan in set([np.nan])

True

In [36]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [38]:
"""
[[0, 0, 0, 0, 0],
[1, 0, 0, 0, 0],
[0, 2, 0, 0, 0],
[0, 0, 3, 0, 0],
[0, 0, 0, 4, 0]
]
"""
np.diag([1, 2, 3, 4],k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [45]:
arr = np.zeros((8, 8))
arr[::2, ::2] = 1
arr[1::2, 1::2] = 1
arr

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [59]:
# sol 1
a = np.arange(6 * 7 * 8).reshape(6, 7, 8)
print(np.where(a == 100))
# sol 2
np.unravel_index(100, (6, 7, 8))

(array([1]), array([5]), array([4]))


(np.int64(1), np.int64(5), np.int64(4))

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [62]:
a = np.array([[0, 1], [1, 0]])
b = np.tile(a, (4, 4))
print(b)
b.shape

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


(8, 8)

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [65]:
a = np.random.rand(5, 5)
(a - a.mean())/a.std()

array([[-1.4115322 ,  0.2416464 , -0.51711469,  0.36606371, -1.48092117],
       [ 1.17085347,  1.49824009,  1.48343298,  0.77945902, -1.21007685],
       [ 0.80711165, -1.54885404, -1.55676434, -0.58863676, -0.05868638],
       [ 0.84610892,  0.56637658, -0.19593372, -0.74914288,  1.574138  ],
       [-0.25926267, -0.17832259, -1.10238168,  0.92446853,  0.59973061]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [69]:
dtype = np.dtype([('R', 'u4'), ('G', 'u4'), ('B', 'u4'), ('A', 'u4')])
dtype

dtype([('R', '<u4'), ('G', '<u4'), ('B', '<u4'), ('A', '<u4')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [70]:
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)
A @ B

array([[0.65840454, 0.30411377],
       [1.26307709, 0.50943383],
       [0.84211651, 0.39594413],
       [0.77044982, 0.26292216],
       [0.72161525, 0.24454266]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [71]:
a = np.arange(20)
mask = (a >= 3) & (a <= 8)
a[mask] *= -1
a 

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [74]:
print(sum(range(5), -1))
print(np.sum(range(5), -1))
range(5)

9
10


range(0, 5)

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [75]:
np.array(0) / np.array(0)

/var/folders/pd/rks0rhrj499g669rkntv95y40000gn/T/ipykernel_67970/873513115.py:1: RuntimeWarning: invalid value encountered in divide
  np.array(0) / np.array(0)


np.float64(nan)

In [76]:
np.array(0) // np.array(0)

/var/folders/pd/rks0rhrj499g669rkntv95y40000gn/T/ipykernel_67970/2018018105.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


np.int64(0)

In [77]:
np.array([np.nan]).astype(int).astype(float)

/var/folders/pd/rks0rhrj499g669rkntv95y40000gn/T/ipykernel_67970/699728972.py:1: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float)


array([0.])

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

In [80]:
A = np.arange(1, 10)
B = np.arange(3, 12)
np.intersect1d(A, B)

array([3, 4, 5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [81]:
np.sqrt(-1) == np.emath.sqrt(-1)

/var/folders/pd/rks0rhrj499g669rkntv95y40000gn/T/ipykernel_67970/244602691.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


np.False_

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [86]:
print(np.datetime64('today'))
print(np.datetime64('today') - np.timedelta64(1))
print(np.datetime64('today') + np.timedelta64(1))

2026-03-22
2026-03-21
2026-03-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [89]:
np.arange('2016-07', '2016-08', dtype='datetime64[D]')

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [96]:
rng = np.random.default_rng(seed=12345)
A = rng.normal(loc = 4, scale=0.5, size=(10,))
print(np.ceil(A))
print(np.floor(A))
print(np.round(A))
print(np.modf(A)[1])
print(A.astype(int))

[4. 5. 4. 4. 4. 4. 4. 5. 5. 4.]
[3. 4. 3. 3. 3. 3. 3. 4. 4. 3.]
[3. 5. 4. 4. 4. 4. 3. 4. 4. 3.]
[3. 4. 3. 3. 3. 3. 3. 4. 4. 3.]
[3 4 3 3 3 3 3 4 4 3]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [98]:
np.tile(np.arange(5), (5, 1))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [99]:
np.random.randint(2, 20, size=(1, 10))

array([[12, 14, 18,  9, 19, 19, 15, 16,  7, 12]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [117]:
np.random.uniform(low=0., high=1, size=(1, 10))

array([[0.96991205, 0.09390072, 0.67260212, 0.44375022, 0.86814225,
        0.17714979, 0.69262595, 0.83811529, 0.94461422, 0.68324803]])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [123]:
A = np.random.rand(1, 10)
A.sort()
A

array([[0.02564207, 0.34124783, 0.38019562, 0.39882278, 0.47918188,
        0.51908179, 0.53360255, 0.58017237, 0.60790509, 0.76488326]])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [125]:
%timeit np.arange(10).cumsum()[-1]

469 ns ± 11.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [126]:
%timeit np.sum(np.arange(10))

1.11 µs ± 14.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


#### 42. Consider two random arrays A and B, check if they are equal (★★☆)

In [154]:
A = np.random.randint(low=0, high=2, size=(1, 10))
B = np.random.randint(low=0, high=2, size=(1, 10))
np.all(A == B)

np.False_

#### 43. Make an array immutable (read-only) (★★☆)

In [160]:
A = np.arange(10)
A.flags.writeable = False
A[0] = 20
A

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [169]:
A = np.random.randint(0,20, (10, 2))
B = np.zeros_like(A, dtype='float64')
B[:, 0] = ((A ** 2).sum(axis=1))**0.5
B[:, 1] = np.arctan(A / A[:,::-1])[:, 1]
B

array([[16.40121947,  0.65569563],
       [10.        ,  0.92729522],
       [15.5241747 ,  0.26060239],
       [21.02379604,  0.44237422],
       [17.11724277,  0.11710874],
       [15.62049935,  0.69473828],
       [20.        ,  0.64350111],
       [16.76305461,  1.26791146],
       [21.63330765,  0.98279372],
       [20.1246118 ,  0.46364761]])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [170]:
A = np.random.rand(10)
A[A.argmax()] = 0
A

array([0.85272802, 0.22554133, 0.37691416, 0.46173281, 0.480906  ,
       0.4351804 , 0.        , 0.70601901, 0.63117065, 0.04984203])

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [185]:
dtype = [('x', 'f8'), ('y', 'f8')]
A = np.zeros((5, 5), dtype=dtype)
A['x'], A['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
A


array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [191]:
x = np.linspace(1., 10)
y = x + 0.5
X, Y = np.meshgrid(x, y)
C = 1/(X - Y)
print(C)
# or
C = 1/np.subtract.outer(x, y)
C

[[-2.         -3.16129032 -7.53846154 ...  0.1229611   0.1202454
   0.11764706]
 [-1.46268657 -2.         -3.16129032 ...  0.12580231  0.1229611
   0.1202454 ]
 [-1.15294118 -1.46268657 -2.         ...  0.12877792  0.12580231
   0.1229611 ]
 ...
 [-0.10949721 -0.11174458 -0.11408615 ... -2.         -3.16129032
  -7.53846154]
 [-0.10733844 -0.10949721 -0.11174458 ... -1.46268657 -2.
  -3.16129032]
 [-0.10526316 -0.10733844 -0.10949721 ... -1.15294118 -1.46268657
  -2.        ]]


array([[-2.        , -1.46268657, -1.15294118, ..., -0.10949721,
        -0.10733844, -0.10526316],
       [-3.16129032, -2.        , -1.46268657, ..., -0.11174458,
        -0.10949721, -0.10733844],
       [-7.53846154, -3.16129032, -2.        , ..., -0.11408615,
        -0.11174458, -0.10949721],
       ...,
       [ 0.1229611 ,  0.12580231,  0.12877792, ..., -2.        ,
        -1.46268657, -1.15294118],
       [ 0.1202454 ,  0.1229611 ,  0.12580231, ..., -3.16129032,
        -2.        , -1.46268657],
       [ 0.11764706,  0.1202454 ,  0.1229611 , ..., -7.53846154,
        -3.16129032, -2.        ]])

#### 48. Print the minimum and maximum representable values for each numpy scalar type (★★☆)

In [195]:
print(np.iinfo(np.int8))
print(np.finfo(np.float64))

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
smallest_normal = 2.2250738585072014e-308   smallest_subnormal = 4.9406564584124654e-324
---------------------------------------------------------------



#### 49. How to print all the values of an array? (★★☆)

In [214]:
print(np.ones((40, 40)))

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [215]:
np.set_printoptions(threshold=float("inf"))
A = np.ones((40, 40))
print(A)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [220]:
A = np.arange(20)
scalar = 15.6
A[np.argmin(np.abs(A - scalar))]

np.int64(16)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [222]:
dtype = [
    ('pos', [('x', 'f8'), ('y', 'f8')]), 
    ('color', [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])
    ]
a = np.zeros(10, dtype=dtype)
a

array([((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0)),
       ((0., 0.), (0, 0, 0)), ((0., 0.), (0, 0, 0))],
      dtype=[('pos', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', 'u1'), ('g', 'u1'), ('b', 'u1')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [ ]:
A = rng.normal(loc = 0, scale=100, size=(100, 2))
A = np.arange(6).reshape(3, 2)
np.
#pp_dist = np.sqrt(np.outer(nA ** 2), axis=1))
#pp_dist

array([1.        , 3.60555128, 6.40312424])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) array in place?

In [233]:
np.arange(10).astype(np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [246]:
import io
s = io.StringIO('''1, 2, 3, 4, 5
                6, , , 7, 8
                 , , 9, 10, 11
                ''')

np.genfromtxt(s, delimiter=',', dtype=int, filling_values=0)

array([[ 1,  2,  3,  4,  5],
       [ 6,  0,  0,  7,  8],
       [ 0,  0,  9, 10, 11]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [248]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(0, 4) 5
(1, 0) 6
(1, 1) 
(1, 2) 
(1, 3) 7
(1, 4) 8
(2, 0) 
(2, 1) 
(2, 2) 9
(2, 3) 10
(2, 4) 11


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to multiply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extracts a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combination of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)